### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by avysk** [UltiRequiem/coc-cl#7]
`:CocInstall coc-cl` gives me `coc-cl main file lib/index.js not found, you may need to build the project.`, both on Windows and on FreeBSD.

**Comment by avysk** [comment]
I just got the same result on Ubuntu 23.04.

**Comment by anta40** [comment]
Yep same problem on MacOS Monterey.

**Comment by steve-anunknown** [comment]
Same problem on Ubuntu 22.04

**Comment by UltiRequiem** [comment]
I will try to find some time to work on this next week, but if you need this is probs just cloning the repo + building in your self and telling coc where to find the extension

**Comment by shmup** [comment]
Only posting this in a closed ticket, because I didn't see anyone acknowledge it was fixed. Though, it remained quiet for a little while so maybe it was!

Install finished

- ✗ coc-cl main file lib/index.js not found, you may need to build the project.

I've manually resolved it. How I managed this for future reference is:

1. `:CocInstall coc-ls`
2. `cd ~/.config/coc/extensions/node_modules/coc-cl`
3. copied over lib and lock from source I had cloned elsewhere
4. `yarn` 

cool, now it's installed. also that solution isn't the only way to fix it atm, just sharing what I did right or wrong, heh

**Comment by avysk** [comment]
Closing this bug is wishful thinking. The bug claimed that `:CocInstall coc-cl` fails, and it still fails in the same way. I am very happy that this might be fixed in the repository, but the bug as is is perfectly valid and reproducible. And it is was **closed** four months ago.

**Comment by UltiRequiem** [comment]
I just uploaded a new version

**Comment by cxwx** [comment]
dead?

**Comment by UltiRequiem** [comment]
no
